spring:
  application:
    name: studystrike-backend
  
  datasource:
    url: jdbc:h2:mem:studystrike
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    com.studystrike: DEBUG
    org.springframework.security: DEBUG

# H2 Console (for development)
h2:
  console:
    enabled: true
    path: /h2-console 
jwt:
  secret: this_is_a_very_long_and_secure_jwt_secret_key_1234567890
  expiration:
    ms: 86400000 